---
- name: create mongodb{{ dbPort }} | 1st
  file: path=/work/mongodb{{ dbPort }} state=directory mode=0755
  tags: mongodb32

- name: create mongodb{{ dbPort }} | 2nd
  file: path=/work/mongodb{{ dbPort }}/{{ item.dir }} state=directory mode=0755
  tags: mongodb32
  with_items:
    - { dir: 'etc' }
    - { dir: 'key' }
    - { dir: 'var' }
    - { dir: 'log' }
    - { dir: 'tmp' }

- name: create mongodb{{ dbPort }} | 3rd
  template: src=mongodb32.conf.j2 dest=/work/mongodb{{ dbPort }}/etc/mongodb{{ dbPort }}.conf mode=0644
  tags: mongodb32

- name: create mongodb{{ dbPort }} | 4th
  template: src=secret.key dest=/work/mongodb{{ dbPort }}/key/keyFile mode=0400
  tags: mongodb32

- name: create mongodb{{ dbPort }} | 5th
  template: src=service.sh.j2 dest=/etc/init.d/mongod{{ dbPort }} mode=0755
  tags: mongodb32
  notify: started mongod 
