---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.
#
#- name: create mongodb
#  gather_facts: false
#  hosts: mongod 
#  roles:
#  - role: mongod 
#  tags: init instances

#- name: init replset
#  gather_facts: false
#  hosts: primary 
#  roles:
#  - role: replset 
#  tags: init replset

- name: init configsvr
  gather_facts: false
  hosts: configsvr
  roles:
  - role: mongoc
  tags: init configsvr 
